[workspace]
members = [
    "compiler/zeque",
    "compiler/zeque_ast",
    "compiler/zeque_lexer",
    "compiler/zeque_parse",
    "zequefmt",
    # "language_server",
    # "runtime",
]
resolver = "2"
