[package]
name = "zeque_parse"
version = "0.1.0"
edition = "2021"

[dependencies]
peg = "0.8.4"
smol_str = "0.3.1"
miette = "7.2.0"
thiserror = "1.0.64"
zeque_lexer = { path = "../zeque_lexer" }
zeque_ast = { path = "../zeque_ast" }
